version: '3.8'

# usage:
# docker-compose up -d

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: md_app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    networks:
      - service-network
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/pgsql:/var/lib/postgresql/data
    secrets:
      - postgres-password
    healthcheck:
      test: pg_isready -U md_app -d market_data
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - NODE_ENV=local
    ports:
      - 8050:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    networks:
      - service-network
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: md_app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      DATABASE_URL: db
    secrets:
      - postgres-password
  data-generator:
    build:
      context: .
      dockerfile: data_generator/Dockerfile
      args:
        - NODE_ENV=local
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    networks:
      - service-network
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: md_app
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      DATABASE_URL: db
    secrets:
      - postgres-password
networks:
    service-network:
        driver: bridge
secrets:
  postgres-password:
    file: secrets/postgres-password.txt



